### ISSUE TITLE
webpack should be a peer dependency

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [JetBrains/svg-sprite-loader#450]
`svg-sprite-loader` uses `webpack` but doesn't declare it as a peer dependency, which generates warnings when using the Yarn PnP (plug and play) feature:

```
Error: svg-sprite-loader tried to access webpack, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

To fix this problem, I believe `svg-sprite-loader` should list `webpack` in its [peerDependencies](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#peerdependencies) or [optionalDependencies](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#optionaldependencies) section.

**Comment by Bosch-Eli-Black** [comment]
As a temporary workaround, it's possible to add this to one's `.yarnrc.yml` file:

```yml
# svg-sprite-loader depends on webpack but doesn't yet list it as a peer dependency.
#
# This gives us an error while compiling, so we patch svg-sprite-loader to add webpack as a peerDependency.
#
# Bug report: https://github.com/JetBrains/svg-sprite-loader/issues/450
packageExtensions:
    svg-sprite-loader@*:
        peerDependencies:
            "webpack": "*"
```
