### ISSUE TITLE
Invalid paths in css file

### ISSUE THREAD

**Issue by ezoterik** [JetBrains/svg-sprite-loader#477]
**Do you want to request a feature, report a bug or ask a question?**

Bug or question

**What is the current behavior?**

After runing `npm run dev` I get (in `dist/css/main.css`):

```css
body {
    background-image: url(b9a42b87318abfe2a6e6.svg);
}
```

**What is the expected behavior?**

```css
body {
    background-image: url("./images/sprite.svg#error404");
}
```

**If the current behavior is a bug, please provide the steps to reproduce, at least part of webpack config with loader configuration and piece of your code.**
**The best way is to create repo with minimal setup to demonstrate a problem (package.json, webpack config and your code).**
**It you don't want to create a repository - create a [gist](http://gist.github.com) with multiple files**

https://github.com/ezoterik/test-svg

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please tell us about your environment:**

- Node.js version: v14.18.1
- webpack version: 5.61.0
- svg-sprite-loader version: 6.0.11
- OS type & version: Windows 10 (WSL2)

**Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)**

Perhaps I am doing something wrong?
